# Generated by Django 3.2.9 on 2022-01-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.pngrepo.com/png/51691/512/placeholder.png', max_length=500),
        ),
    ]
